apiVersion: v1
kind: Namespace
metadata:
  name: nhie
---
apiVersion: v1
kind: Service
metadata:
  name: nhie-backend-service
  namespace: nhie
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: NodePort
  selector:
    app: nhie-backend
  ports:
    - name: http
      protocol: TCP
      port: 60000
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nhie-backend-ingress
  namespace: nhie
spec:
  rules:
    - host: nhie.saufautom.at
      http:
        paths:
        - backend:
            serviceName: nhie-backend-service
            servicePort: 60000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhie-backend
  namespace: nhie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nhie-backend
  template:
    metadata:
      labels:
        app: nhie-backend
    spec:
      containers:
      - name: nhie-backend
        image: torbencarstens/neverhaveiever{{TAG}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
