name: Build/Publish docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build bundle.js"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: Run Workflow
        id: write_kubeconfig
        uses: timheuer/base64-to-file@v1
        with:
          fileName: kubeconfig
          encodedString: ${{ secrets.K8SCONF }}
      - run: cat kubeconfig | md5sum
      - run: cat kubeconfig | wc -l
      - run: sed -i -e "s#{{TAG}}#$(echo ${GITHUB_SHA})#g" src/App.fs
      - run: npm install
      - run: npm run prod
      - uses: actions/upload-artifact@v1
        with:
          name: bundlejs
          path: public/bundle.js
  build_push_docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Login to dockerhub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u torbencarstens --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA})
      - uses: actions/download-artifact@v1
        with:
          name: bundlejs
      - name: Move artifact into public
        run: mv bundlejs/bundle.js public/bundle.js
      - name: Build the tagged Docker image
        run: docker build -t torbencarstens/neverhaveiever:${{steps.vars.outputs.tag}} .
      - name: Push the tagged Docker image
        run: docker push torbencarstens/neverhaveiever:${{steps.vars.outputs.tag}}
  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: build_push_docker
    steps:
      - uses: actions/checkout@v1
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA})
      - name: get kube config
        run: 'echo $K8SCONF | base64 -d > $GITHUB_WORKSPACE/.kubeconfig'
        env:
          K8SCONF: ${{ secrets.K8SCONF }}
      - name: update tag in manifest.yml
        run: sed -i -e "s#{{TAG}}#:$(echo ${{steps.vars.outputs.tag}})#g" .kubernetes/manifest.yaml
      - name: apply config
        run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f .kubernetes/manifest.yaml

